server:
  port: 7000
spring:
  datasource:
    #    url: jdbc:postgresql://localhost:5432/postgres
    #    username: postgres
    #    password: postgres
    #    driver-class-name: org.postgresql.Driver
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    hibernate:
      ddl-auto: update
    show-sql: true